[build]
  command = "npm install && npm run build"
  functions = "functions"

[functions]
  included_files = ["assets/*","views/*","*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/core/:splat"
  status = 200
  force = true
